#!/bin/sh
#
# Foretag en søgning i concieggs' omfattende hukommelse efter detaljer
# omkring et givent emne.


lookup() {
     cat $CONCIEGGS_DB_DIR/fakta | sort -V | grep -F -i "$*"
}

if [ "$*" ]; then
    if ! lookup "$*"; then
        echo "I know nothing about $*."
    fi
else
     echo "Explain what?"
fi
