#!/bin/sh
#
# Husk et givent faktum til senere opslag via 'forklar'.


if [ $# -gt 0 ]; then
    echo "$@" >> $CONCIEGGS_DB_DIR/fakta
    echo "I'll remember it!"
else
    echo "But what am I supposed to remember?"
fi 
